import type { AppState, FacePreset, Pet, User } from './types'
import { DEFAULT_KR_TARGET } from './types'
import { basePetForSpecies } from './catalog'
import { MOUNT_ID } from './types'
import { addDays, weekIdFromDate } from './rules'

const face = (n: number): FacePreset => ({
  eye_size: 40 + n * 8,
  eye_spacing: 45 + n * 5,
  muzzle_length: 35 + n * 7,
  ear_tilt: 30 + n * 10,
  brow_height: 50,
  cheek: 40 + n * 6,
  body_round: 50 + n * 4,
})

function pet(
  id: string,
  ownerId: string,
  species: Pet['species'],
  nickname: string,
  n: number,
  motto: string,
): Pet {
  return {
    id,
    ownerId,
    species,
    nickname,
    name: nickname,
    motto,
    face: face(n),
    hunger: 55 + n * 5,
    mood: 60 + n * 4,
    growth: 16 + n * 8,
    lastCareDate: '2026-08-23',
    lastCareGrowthDate: '2026-08-23',
    lastCareAt: n === 3 ? '2026-08-22T08:00:00' : '2026-08-23T20:00:00',
    skinId: n % 2 === 0 ? 'skin_basic_leaf' : 'skin_basic_cloud',
    mountId: n === 0 ? MOUNT_ID : null,
    headwearId: n === 0 ? 'hw_leaf' : 'hw_bow',
    clothesId: n % 2 === 0 ? 'cl_scarf' : 'cl_cloud',
    shoesId: n === 3 ? 'sh_socks' : 'sh_none',
    basePetId: basePetForSpecies(species).id,
    paletteId: basePetForSpecies(species).palette,
    marking: basePetForSpecies(species).marking,
    expression: n === 3 ? 'tired' : 'idle',
  }
}

export const SHOP_ITEMS = [
  { id: 'skin_basic_leaf', name: '叶绿围巾', cost: 4 as const, kind: 'skin' as const, rare: false },
  { id: 'skin_basic_cloud', name: '云朵围脖', cost: 4 as const, kind: 'skin' as const, rare: false },
  { id: 'skin_mid_star', name: '星点披风', cost: 8 as const, kind: 'skin' as const, rare: false },
  { id: 'skin_mid_ink', name: '墨纹马甲', cost: 8 as const, kind: 'skin' as const, rare: false },
  { id: 'skin_high_aurora', name: '极光外衣', cost: 12 as const, kind: 'skin' as const, rare: false },
  { id: 'skin_high_festival', name: '节庆花纹', cost: 12 as const, kind: 'skin' as const, rare: false },
  { id: 'skin_rare_week', name: '周赛银辉', cost: 12 as const, kind: 'skin' as const, rare: true },
  { id: 'skin_rare_achieve', name: '成就金纹', cost: 12 as const, kind: 'skin' as const, rare: true },
  { id: MOUNT_ID, name: '课桌垫坐骑', cost: 8 as const, kind: 'mount' as const, rare: true },
]

export function createSeed(): AppState {
  const today = '2026-08-24'
  const week = weekIdFromDate(today)
  const prevWeek = weekIdFromDate(addDays(today, -7))
  const users: User[] = [
    { id: 't1', name: '叶老师', role: 'teacher', code: 'teacher', classId: 'c1', classIds: ['c1'], dnd: false },
    { id: 's1', name: '林小舟', role: 'student', code: 'student', classId: 'c1', dnd: false, seat: { row: 1, col: 2 } },
    { id: 's2', name: '陈安安', role: 'student', code: 'student', classId: 'c1', dnd: false, seat: { row: 1, col: 3 } },
    { id: 's3', name: '周牧野', role: 'student', code: 'student', classId: 'c1', dnd: true, seat: { row: 1, col: 4 } },
    { id: 's4', name: '苏晚晚', role: 'student', code: 'student', classId: 'c1', dnd: false, seat: { row: 1, col: 5 } },
    { id: 'p1', name: '林妈妈', role: 'parent', code: 'parent', studentId: 's1', classId: 'c1', dnd: false },
  ]

  return {
    schoolName: '阳光实验中学',
    className: '初二（3）班',
    classes: [
      { id: 'c1', name: '初二（3）班' },
    ],
    classLayout: { cols: 6, rows: 5 },
    users,
    pets: [
      pet('pet1', 's1', 'fox', '赤赤', 0, '赤心向前'),
      pet('pet2', 's2', 'owl', '咕咕', 1, '夜里也认真想'),
      pet('pet3', 's3', 'otter', '滑滑', 2, '慢慢游也能到'),
      pet('pet4', 's4', 'rabbit', '团团', 3, '软软也要努力'),
    ],
    reports: [
      {
        id: 'r1',
        authorId: 's1',
        date: '2026-08-24',
        category: 'quality',
        evidence: '数学订正本第3页已重做，老师签字。',
        status: 'auto_posted',
        peerFacts: 2,
        peerDoubts: 0,
        queuedAt: '2026-08-23',
        submittedAt: '2026-08-23T10:00:00',
        credited: true,
      },
      {
        id: 'r2',
        authorId: 's2',
        date: '2026-08-24',
        category: 'correction',
        evidence: '英语错题本闭环：错因+再练两题。',
        status: 'in_review',
        peerFacts: 1,
        peerDoubts: 0,
        queuedAt: null,
        submittedAt: '2026-08-24T08:10:00',
        credited: false,
      },
      {
        id: 'r3',
        authorId: 's3',
        date: '2026-08-24',
        category: 'quiz_self',
        evidence: '课前自测 8/10，对照答案订了两处概念。',
        status: 'queued',
        peerFacts: 1,
        peerDoubts: 0,
        queuedAt: '2026-08-24',
        submittedAt: '2026-08-24T08:20:00',
        credited: false,
      },
      {
        id: 'r4',
        authorId: 's4',
        date: '2026-08-24',
        category: 'participation',
        evidence: '小组汇报主动补充了一条例子。',
        status: 'queued',
        peerFacts: 0,
        peerDoubts: 0,
        queuedAt: '2026-08-24',
        submittedAt: '2026-08-24T08:30:00',
        credited: false,
      },
      {
        id: 'r5',
        authorId: 's1',
        date: '2026-08-23',
        category: 'participation',
        evidence: '值日按时完成。',
        status: 'auto_posted',
        peerFacts: 1,
        peerDoubts: 0,
        queuedAt: '2026-08-23',
        submittedAt: '2026-08-23T16:00:00',
        credited: true,
      },
      {
        id: 'r6',
        authorId: 's2',
        date: '2026-08-23',
        category: 'quality',
        evidence: '作文第二稿比第一稿多了具体细节。',
        status: 'auto_posted',
        peerFacts: 2,
        peerDoubts: 0,
        queuedAt: '2026-08-23',
        submittedAt: '2026-08-23T16:10:00',
        credited: true,
      },
      {
        id: 'r7',
        authorId: 's4',
        date: '2026-08-23',
        category: 'correction',
        evidence: '物理公式写错已订正并讲给同桌听。',
        status: 'in_review',
        peerFacts: 0,
        peerDoubts: 1,
        queuedAt: null,
        submittedAt: '2026-08-23T16:20:00',
        credited: false,
      },
      {
        id: 'r8',
        authorId: 's1',
        date: '2026-08-17',
        category: 'quiz_self',
        evidence: '上周自测 6/10，记下两处公式。',
        status: 'posted',
        peerFacts: 1,
        peerDoubts: 0,
        queuedAt: '2026-08-17',
        submittedAt: '2026-08-17T09:00:00',
        credited: true,
      },
      {
        id: 'r9',
        authorId: 's1',
        date: '2026-08-22',
        category: 'quiz_self',
        evidence: '本周自测 8/10，比上周少错两题。',
        status: 'posted',
        peerFacts: 2,
        peerDoubts: 0,
        queuedAt: '2026-08-22',
        submittedAt: '2026-08-22T09:00:00',
        credited: true,
      },
      {
        id: 'r10',
        authorId: 's3',
        date: '2026-08-16',
        category: 'quiz_self',
        evidence: '二班自测 5/10。',
        status: 'posted',
        peerFacts: 1,
        peerDoubts: 0,
        queuedAt: '2026-08-16',
        submittedAt: '2026-08-16T09:10:00',
        credited: true,
      },
      {
        id: 'r11',
        authorId: 's3',
        date: '2026-08-21',
        category: 'quiz_self',
        evidence: '二班自测 7/10，对照上周少错。',
        status: 'posted',
        peerFacts: 1,
        peerDoubts: 0,
        queuedAt: '2026-08-21',
        submittedAt: '2026-08-21T09:10:00',
        credited: true,
      },
    ],
    reviews: [
      { id: 'v1', reportId: 'r2', reviewerId: 's1', date: '2026-08-24', verdict: 'fact' },
      { id: 'v3', reportId: 'r3', reviewerId: 's4', date: '2026-08-23', verdict: 'fact' },
    ],
    ledger: [
      { id: 'l1', studentId: 's1', date: '2026-08-23', delta: 2, kind: 'earn', reason: '作业质量' },
      { id: 'l2', studentId: 's1', date: '2026-08-23', delta: -2, kind: 'spend', reason: '喂食' },
      { id: 'l3', studentId: 's2', date: '2026-08-23', delta: 2, kind: 'earn', reason: '订正闭环' },
      { id: 'l4', studentId: 's3', date: '2026-08-23', delta: 1, kind: 'earn', reason: '课堂参与' },
      { id: 'l5', studentId: 's4', date: '2026-08-23', delta: 4, kind: 'earn', reason: '作业质量+自测' },
      { id: 'l6', studentId: 's4', date: '2026-08-24', delta: -2, kind: 'spend', reason: '抚摸' },
      { id: 'l7', studentId: 's1', date: '2026-08-22', delta: 2, kind: 'earn', reason: '自测对照', ref: 'r9' },
      { id: 'l8', studentId: 's1', date: '2026-08-22', delta: -2, kind: 'spend', reason: '喂食' },
      { id: 'l9', studentId: 's1', date: '2026-08-21', delta: -2, kind: 'spend', reason: '抚摸' },
      { id: 'l10', studentId: 's2', date: '2026-08-22', delta: -2, kind: 'spend', reason: '喂食' },
      { id: 'l11', studentId: 's3', date: '2026-08-21', delta: 2, kind: 'earn', reason: '自测对照', ref: 'r11' },
      { id: 'l12', studentId: 's3', date: '2026-08-21', delta: -2, kind: 'spend', reason: '抚摸' },
      { id: 'l13', studentId: 's4', date: '2026-08-22', delta: -2, kind: 'spend', reason: '喂食' },
      { id: 'auto-r1', studentId: 's1', date: '2026-08-24', delta: 2, kind: 'earn', reason: '超时有效入账 · 作业质量', ref: 'r1' },
      { id: 'auto-r5', studentId: 's1', date: '2026-08-24', delta: 1, kind: 'earn', reason: '超时有效入账 · 课堂参与', ref: 'r5' },
      { id: 'auto-r6', studentId: 's2', date: '2026-08-24', delta: 2, kind: 'earn', reason: '超时有效入账 · 作业质量', ref: 'r6' },
    ],
    visits: [
      { id: 'vi1', fromId: 's1', toId: 's2', date: '2026-08-23', type: 'visit' },
      { id: 'vi2', fromId: 's2', toId: 's1', date: '2026-08-23', type: 'emoji', emoji: '✨' },
    ],
    squads: [
      { id: 'sq1', name: '赤云小队', memberIds: ['s1', 's2'] },
      { id: 'sq2', name: '滑团小队', memberIds: ['s3', 's4'] },
    ],
    squadWeeks: [
      { weekId: week, teamId: 'sq1', points: 7, comboUsed: false },
      { weekId: week, teamId: 'sq2', points: 4, comboUsed: true },
    ],
    honors: [
      { id: 'h1', weekId: prevWeek, studentId: 's2', label: '互助小星' },
      { id: 'h2', weekId: prevWeek, studentId: 's4', label: '订正达人' },
    ],
    unlocked: {
      s1: ['skin_basic_leaf', MOUNT_ID],
      s2: ['skin_basic_cloud'],
      s3: ['skin_basic_leaf'],
      s4: ['skin_basic_cloud'],
    },
    unlockedAchievements: {
      s1: ['streak_mount'],
    },
    inClassHour: { c1: false },
    activeWeek: week,
    lastSettledWeek: prevWeek,
    session: null,
    todayOverride: today,
    classScores: { s1: 0, s2: 0, s3: 0, s4: 0 },
    classScoreWeek: week,
    personalOkrs: {
      s1: { weekId: week, objective: '本周订正全做完', krTarget: DEFAULT_KR_TARGET, krDone: 2, lastTickDate: '2026-08-23' },
      s2: { weekId: week, objective: '晚自习专注四次', krTarget: DEFAULT_KR_TARGET, krDone: 1, lastTickDate: null },
      s3: { weekId: week, objective: '本周订正全做完', krTarget: DEFAULT_KR_TARGET, krDone: 0, lastTickDate: null },
      s4: { weekId: week, objective: '晚自习专注四次', krTarget: DEFAULT_KR_TARGET, krDone: 1, lastTickDate: null },
    },
    classOkr: { weekId: week, objective: '作业准时率', doneCount: 1 },
    classSession: { active: false, deltas: {}, classKrMoved: false },
    krTicks: [],
    dailyMoods: [],
    baseHabits: [],
  }
}
